name: CI
on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 22
    - name: Create env file
      run: echo "${{ secrets.CI_ENV }}" > .env
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Start apps
      env:
        PUBLIC_VAPID_KEY: ${{ secrets.PUBLIC_VAPID_KEY }}
      run: docker compose up -d --wait
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm test
    - uses: actions/upload-artifact@v6
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Stop apps
      run: docker compose down
